using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestEWS.CorpPortalIntegration
{
    public static class Constants
    {
        public static readonly IList<string> Countries = new List<string>();

        public static readonly IList<string> ModuleNames = new List<string>();

        public static readonly IList<string> ProductVersions = new List<string>();

        public static readonly string WebGuid = "6dcf9aed-9c94-4a56-ac01-469aa4c4c505";

        public static readonly int MaxExpirationPeriodMonths = 14;

        static Constants()
        {
            InitCountries();
            InitModules();
            InitProductVersions();
        }

        private static void InitCountries()
        {
            Countries.Add("Afghanistan");
            Countries.Add("Aland");
            Countries.Add("Albania");
            Countries.Add("Algeria");
            Countries.Add("American Samoa");
            Countries.Add("Andorra");
            Countries.Add("Angola");
            Countries.Add("Anguilla");
            Countries.Add("Antarctica");
            Countries.Add("Antigua and Barbuda");
            Countries.Add("Argentina");
            Countries.Add("Armenia");
            Countries.Add("Aruba");
            Countries.Add("Ascension");
            Countries.Add("Ashmore and Cartier Islands");
            Countries.Add("Australia");
            Countries.Add("Australian Antarctic Territory");
            Countries.Add("Austria");
            Countries.Add("Azerbaijan");
            Countries.Add("Bahamas, The");
            Countries.Add("Bahrain");
            Countries.Add("Baker Island");
            Countries.Add("Bangladesh");
            Countries.Add("Barbados");
            Countries.Add("Belarus");
            Countries.Add("Belgium");
            Countries.Add("Belize");
            Countries.Add("Benin");
            Countries.Add("Bermuda");
            Countries.Add("Bhutan");
            Countries.Add("Bolivia");
            Countries.Add("Bosnia and Herzegovina");
            Countries.Add("Botswana");
            Countries.Add("Bouvet Island");
            Countries.Add("Brazil");
            Countries.Add("British Antarctic Territory");
            Countries.Add("British Indian Ocean Territory");
            Countries.Add("British Sovereign Base Areas");
            Countries.Add("British Virgin Islands");
            Countries.Add("Brunei");
            Countries.Add("Bulgaria");
            Countries.Add("Burkina Faso");
            Countries.Add("Burundi");
            Countries.Add("Cambodia");
            Countries.Add("Cameroon");
            Countries.Add("Canada");
            Countries.Add("Cape Verde");
            Countries.Add("Cayman Islands");
            Countries.Add("Central African Republic");
            Countries.Add("Chad");
            Countries.Add("Chile");
            Countries.Add("China, People's Republic of");
            Countries.Add("China, Republic of (Taiwan)");
            Countries.Add("Christmas Island");
            Countries.Add("Clipperton Island");
            Countries.Add("Cocos (Keeling) Islands");
            Countries.Add("Colombia");
            Countries.Add("Comoros");
            Countries.Add("Congo, Democratic Republic of the (Congo – Kinshasa)");
            Countries.Add("Congo, Republic of the (Congo – Brazzaville)");
            Countries.Add("Cook Islands");
            Countries.Add("Coral Sea Islands");
            Countries.Add("Costa Rica");
            Countries.Add("Cote d'Ivoire (Ivory Coast)");
            Countries.Add("Croatia");
            Countries.Add("Cuba");
            Countries.Add("Cyprus");
            Countries.Add("Czech Republic");
            Countries.Add("Denmark");
            Countries.Add("Djibouti");
            Countries.Add("Dominica");
            Countries.Add("Dominican Republic");
            Countries.Add("Ecuador");
            Countries.Add("Egypt");
            Countries.Add("El Salvador");
            Countries.Add("Equatorial Guinea");
            Countries.Add("Eritrea");
            Countries.Add("Estonia");
            Countries.Add("Ethiopia");
            Countries.Add("Falkland Islands (Islas Malvinas)");
            Countries.Add("Faroe Islands");
            Countries.Add("Fiji");
            Countries.Add("Finland");
            Countries.Add("France");
            Countries.Add("French Guiana");
            Countries.Add("French Polynesia");
            Countries.Add("French Southern and Antarctic Lands");
            Countries.Add("Gabon");
            Countries.Add("Gambia, The");
            Countries.Add("Georgia");
            Countries.Add("Germany");
            Countries.Add("Ghana");
            Countries.Add("Gibraltar");
            Countries.Add("Greece");
            Countries.Add("Greenland");
            Countries.Add("Grenada");
            Countries.Add("Guadeloupe");
            Countries.Add("Guam");
            Countries.Add("Guatemala");
            Countries.Add("Guernsey");
            Countries.Add("Guinea");
            Countries.Add("Guinea-Bissau");
            Countries.Add("Guyana");
            Countries.Add("Haiti");
            Countries.Add("Heard Island and McDonald Islands");
            Countries.Add("Honduras");
            Countries.Add("Hong Kong");
            Countries.Add("Howland Island");
            Countries.Add("Hungary");
            Countries.Add("Iceland");
            Countries.Add("India");
            Countries.Add("Indonesia");
            Countries.Add("Iran");
            Countries.Add("Iraq");
            Countries.Add("Ireland");
            Countries.Add("Isle of Man");
            Countries.Add("Israel");
            Countries.Add("Italy");
            Countries.Add("Jamaica");
            Countries.Add("Japan");
            Countries.Add("Jarvis Island");
            Countries.Add("Jersey");
            Countries.Add("Johnston Atoll");
            Countries.Add("Jordan");
            Countries.Add("Kazakhstan");
            Countries.Add("Kenya");
            Countries.Add("Kingman Reef");
            Countries.Add("Kiribati");
            Countries.Add("Korea, Democratic People's Republic of (North Korea)");
            Countries.Add("Korea, Republic of  (South Korea)");
            Countries.Add("Kosovo");
            Countries.Add("Kuwait");
            Countries.Add("Kyrgyzstan");
            Countries.Add("Laos");
            Countries.Add("Latvia");
            Countries.Add("Lebanon");
            Countries.Add("Lesotho");
            Countries.Add("Liberia");
            Countries.Add("Libya");
            Countries.Add("Liechtenstein");
            Countries.Add("Lithuania");
            Countries.Add("Luxembourg");
            Countries.Add("Macau");
            Countries.Add("Macedonia");
            Countries.Add("Madagascar");
            Countries.Add("Malawi");
            Countries.Add("Malaysia");
            Countries.Add("Maldives");
            Countries.Add("Mali");
            Countries.Add("Malta");
            Countries.Add("Marshall Islands");
            Countries.Add("Martinique");
            Countries.Add("Mauritania");
            Countries.Add("Mauritius");
            Countries.Add("Mayotte");
            Countries.Add("Mexico");
            Countries.Add("Micronesia");
            Countries.Add("Midway Islands");
            Countries.Add("Moldova");
            Countries.Add("Monaco");
            Countries.Add("Mongolia");
            Countries.Add("Montenegro");
            Countries.Add("Montserrat");
            Countries.Add("Morocco");
            Countries.Add("Mozambique");
            Countries.Add("Myanmar (Burma)");
            Countries.Add("Nagorno-Karabakh");
            Countries.Add("Namibia");
            Countries.Add("Nauru");
            Countries.Add("Navassa Island");
            Countries.Add("Nepal");
            Countries.Add("Netherlands");
            Countries.Add("Netherlands Antilles");
            Countries.Add("New Caledonia");
            Countries.Add("New Zealand");
            Countries.Add("Nicaragua");
            Countries.Add("Niger");
            Countries.Add("Nigeria");
            Countries.Add("Niue");
            Countries.Add("Norfolk Island");
            Countries.Add("Northern Cyprus");
            Countries.Add("Northern Mariana Islands");
            Countries.Add("Norway");
            Countries.Add("Oman");
            Countries.Add("Pakistan");
            Countries.Add("Palau");
            Countries.Add("Palestinian Territories (Gaza Strip and West Bank)");
            Countries.Add("Palmyra Atoll");
            Countries.Add("Panama");
            Countries.Add("Papua New Guinea");
            Countries.Add("Paraguay");
            Countries.Add("Peru");
            Countries.Add("Peter I Island");
            Countries.Add("Philippines");
            Countries.Add("Pitcairn Islands");
            Countries.Add("Poland");
            Countries.Add("Portugal");
            Countries.Add("Pridnestrovie (Transnistria)");
            Countries.Add("Puerto Rico");
            Countries.Add("Qatar");
            Countries.Add("Queen Maud Land");
            Countries.Add("Reunion");
            Countries.Add("Romania");
            Countries.Add("Ross Dependency");
            Countries.Add("Russia");
            Countries.Add("Rwanda");
            Countries.Add("Saint Barthelemy");
            Countries.Add("Saint Helena");
            Countries.Add("Saint Kitts and Nevis");
            Countries.Add("Saint Lucia");
            Countries.Add("Saint Martin");
            Countries.Add("Saint Pierre and Miquelon");
            Countries.Add("Saint Vincent and the Grenadines");
            Countries.Add("Samoa");
            Countries.Add("San Marino");
            Countries.Add("Sao Tome and Principe");
            Countries.Add("Saudi Arabia");
            Countries.Add("Senegal");
            Countries.Add("Serbia");
            Countries.Add("Seychelles");
            Countries.Add("Sierra Leone");
            Countries.Add("Singapore");
            Countries.Add("Slovakia");
            Countries.Add("Slovenia");
            Countries.Add("Solomon Islands");
            Countries.Add("Somalia");
            Countries.Add("Somaliland");
            Countries.Add("South Africa");
            Countries.Add("South Georgia and the South Sandwich Islands");
            Countries.Add("South Ossetia");
            Countries.Add("Spain");
            Countries.Add("Sri Lanka");
            Countries.Add("Sudan");
            Countries.Add("Suriname");
            Countries.Add("Svalbard");
            Countries.Add("Swaziland");
            Countries.Add("Sweden");
            Countries.Add("Switzerland");
            Countries.Add("Syria");
            Countries.Add("Tajikistan");
            Countries.Add("Tanzania");
            Countries.Add("Thailand");
            Countries.Add("Timor-Leste (East Timor)");
            Countries.Add("Togo");
            Countries.Add("Tokelau");
            Countries.Add("Tonga");
            Countries.Add("Trinidad and Tobago");
            Countries.Add("Tristan da Cunha");
            Countries.Add("Tunisia");
            Countries.Add("Turkey");
            Countries.Add("Turkmenistan");
            Countries.Add("Turks and Caicos Islands");
            Countries.Add("Tuvalu");
            Countries.Add("U.S. Virgin Islands");
            Countries.Add("Uganda");
            Countries.Add("Ukraine");
            Countries.Add("United Arab Emirates");
            Countries.Add("United Kingdom");
            Countries.Add("United States");
            Countries.Add("Uruguay");
            Countries.Add("Uzbekistan");
            Countries.Add("Vanuatu");
            Countries.Add("Vatican City");
            Countries.Add("Venezuela");
            Countries.Add("Vietnam");
            Countries.Add("Wake Island");
            Countries.Add("Wallis and Futuna");
            Countries.Add("Western Sahara");
            Countries.Add("Yemen");
            Countries.Add("Zambia");
            Countries.Add("Zimbabwe");
        }

        private static void InitModules()
        {
            ModuleNames.Add("Organizational Structure");
            ModuleNames.Add("HR Administration");
            ModuleNames.Add("Absence");
            ModuleNames.Add("Compensation");
            ModuleNames.Add("Recruiting");
            ModuleNames.Add("Competence");
            ModuleNames.Add("Goal");
            ModuleNames.Add("Appraisal");
            ModuleNames.Add("Learning");
            ModuleNames.Add("Talent");
        }

        private static void InitProductVersions()
        {
            ProductVersions.Add("ES 2007");
            ProductVersions.Add("ES 2010");
            ProductVersions.Add("ES 2013");
            ProductVersions.Add("Hosted 2013");
            ProductVersions.Add("LHR 2016");
        }
    }
}
